// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using CMS.Data.ModelEntity;

namespace CMS.Data.ModelEntity
{
    public partial class CmsContext
    {
        private CmsContextProcedures _procedures;

        public CmsContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CmsContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public CmsContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CmsContextProcedures
    {
        private readonly CmsContext _context;

        public CmsContextProcedures(CmsContext context)
        {
            _context = context;
        }

        public virtual async Task<SpAccountSearchResult[]> SpAccountSearchAsync(string Keyword, Guid? RoleId, bool? Active, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RoleId",
                    Value = RoleId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "Active",
                    Value = Active ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpAccountSearchResult>("EXEC @returnValue = [dbo].[SpAccountSearch] @Keyword, @RoleId, @Active, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleCommentSearchResult[]> SpArticleCommentSearchAsync(string Keyword, int? ArticleId, bool? Active, string CreateBy, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleId",
                    Value = ArticleId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Active",
                    Value = Active ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "CreateBy",
                    Size = 200,
                    Value = CreateBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleCommentSearchResult>("EXEC @returnValue = [dbo].[SpArticleCommentSearch] @Keyword, @ArticleId, @Active, @CreateBy, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleGetByBlockIdResult[]> SpArticleGetByBlockIdAsync(int? ArticleBlockId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ArticleBlockId",
                    Value = ArticleBlockId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleGetByBlockIdResult>("EXEC @returnValue = [dbo].[SpArticleGetByBlockId] @ArticleBlockId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleGetByCategoryIdResult[]> SpArticleGetByCategoryIdAsync(int? ArticleCategoryId, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ArticleCategoryId",
                    Value = ArticleCategoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleGetByCategoryIdResult>("EXEC @returnValue = [dbo].[SpArticleGetByCategoryId] @ArticleCategoryId, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleGetNewByCategoryIdResult[]> SpArticleGetNewByCategoryIdAsync(int? ArticleCategoryId, int? Number, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ArticleCategoryId",
                    Value = ArticleCategoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Number",
                    Value = Number ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleGetNewByCategoryIdResult>("EXEC @returnValue = [dbo].[SpArticleGetNewByCategoryId] @ArticleCategoryId, @Number", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleGetTopByCategoryIdResult[]> SpArticleGetTopByCategoryIdAsync(int? ArticleCategoryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ArticleCategoryId",
                    Value = ArticleCategoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleGetTopByCategoryIdResult>("EXEC @returnValue = [dbo].[SpArticleGetTopByCategoryId] @ArticleCategoryId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleInMagazinePaperSearchResult[]> SpArticleInMagazinePaperSearchAsync(string Keyword, int? MagazinePaperId, int? ArticleInMagazinePaperStatusId, string UserInReviewId, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MagazinePaperId",
                    Value = MagazinePaperId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleInMagazinePaperStatusId",
                    Value = ArticleInMagazinePaperStatusId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UserInReviewId",
                    Size = 400,
                    Value = UserInReviewId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleInMagazinePaperSearchResult>("EXEC @returnValue = [dbo].[SpArticleInMagazinePaperSearch] @Keyword, @MagazinePaperId, @ArticleInMagazinePaperStatusId, @UserInReviewId, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleInReviewSearchResult[]> SpArticleInReviewSearchAsync(string Keyword, int? ArticleReviewId, int? ArticleInReviewStatusId, string UserInReviewId, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleReviewId",
                    Value = ArticleReviewId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleInReviewStatusId",
                    Value = ArticleInReviewStatusId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UserInReviewId",
                    Size = 400,
                    Value = UserInReviewId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleInReviewSearchResult>("EXEC @returnValue = [dbo].[SpArticleInReviewSearch] @Keyword, @ArticleReviewId, @ArticleInReviewStatusId, @UserInReviewId, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleReviewDetailSearchResult[]> SpArticleReviewDetailSearchAsync(string Keyword, int? ArticleId, string CreateBy, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleId",
                    Value = ArticleId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CreateBy",
                    Size = 200,
                    Value = CreateBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleReviewDetailSearchResult>("EXEC @returnValue = [dbo].[SpArticleReviewDetailSearch] @Keyword, @ArticleId, @CreateBy, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleReviewSearchResult[]> SpArticleReviewSearchAsync(string Keyword, int? ArticleReviewId, int? ArticleReviewStatusId, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleReviewId",
                    Value = ArticleReviewId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleReviewStatusId",
                    Value = ArticleReviewStatusId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleReviewSearchResult>("EXEC @returnValue = [dbo].[SpArticleReviewSearch] @Keyword, @ArticleReviewId, @ArticleReviewStatusId, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpArticleSearchResult[]> SpArticleSearchAsync(string Keyword, string Tags, int? ArticleCategoryId, int? ArticleStatusId, int? ProductBrandId, int? ArticleTypeId, int? ExceptionId, bool? ExceptionArticleTop, DateTime? FromDate, DateTime? ToDate, bool? Efficiency, bool? Active, Guid? CreateBy, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Tags",
                    Size = 400,
                    Value = Tags ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleCategoryId",
                    Value = ArticleCategoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleStatusId",
                    Value = ArticleStatusId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ProductBrandId",
                    Value = ProductBrandId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ArticleTypeId",
                    Value = ArticleTypeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ExceptionId",
                    Value = ExceptionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ExceptionArticleTop",
                    Value = ExceptionArticleTop ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "FromDate",
                    Value = FromDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "ToDate",
                    Value = ToDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "Efficiency",
                    Value = Efficiency ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "Active",
                    Value = Active ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "CreateBy",
                    Value = CreateBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpArticleSearchResult>("EXEC @returnValue = [dbo].[SpArticleSearch] @Keyword, @Tags, @ArticleCategoryId, @ArticleStatusId, @ProductBrandId, @ArticleTypeId, @ExceptionId, @ExceptionArticleTop, @FromDate, @ToDate, @Efficiency, @Active, @CreateBy, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpMagazinePaperSearchResult[]> SpMagazinePaperSearchAsync(string Keyword, int? MagazinePaperId, int? MagazinePaperStatusId, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Keyword",
                    Size = 4000,
                    Value = Keyword ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MagazinePaperId",
                    Value = MagazinePaperId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MagazinePaperStatusId",
                    Value = MagazinePaperStatusId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpMagazinePaperSearchResult>("EXEC @returnValue = [dbo].[SpMagazinePaperSearch] @Keyword, @MagazinePaperId, @MagazinePaperStatusId, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpSearchBreadCrumbByCateResult[]> SpSearchBreadCrumbByCateAsync(int? ArticleCategoryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ArticleCategoryId",
                    Value = ArticleCategoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpSearchBreadCrumbByCateResult>("EXEC @returnValue = [dbo].[SpSearchBreadCrumbByCate] @ArticleCategoryId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<SpUserNotifySearchResult[]> SpUserNotifySearchAsync(int? UserNotifyTypeId, Guid? AspNetUsersId, bool? Readed, int? PageSize, int? CurrentPage, OutputParameter<int?> ItemCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterItemCount = new SqlParameter
            {
                ParameterName = "ItemCount",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserNotifyTypeId",
                    Value = UserNotifyTypeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "AspNetUsersId",
                    Value = AspNetUsersId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "Readed",
                    Value = Readed ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = PageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentPage",
                    Value = CurrentPage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterItemCount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SpUserNotifySearchResult>("EXEC @returnValue = [dbo].[SpUserNotifySearch] @UserNotifyTypeId, @AspNetUsersId, @Readed, @PageSize, @CurrentPage, @ItemCount OUTPUT", sqlParameters, cancellationToken);

            ItemCount.SetValue(parameterItemCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
