// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class MagazinePaper
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [StringLength(1000)]
        public string Name { get; set; }
        [StringLength(500)]
        public string Image { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(200)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditDate { get; set; }
        [StringLength(200)]
        public string LastEditBy { get; set; }
        public int? MagazinePaperStatusId { get; set; }
    }
}