// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class ProductPicture
    {
        [Key]
        public string Id { get; set; }
        public int? ProductId { get; set; }
        /// <summary>
        /// Tên file ảnh đại diện chính
        /// </summary>
        [StringLength(200)]
        public string Image { get; set; }
        public int? Sort { get; set; }
        /// <summary>
        /// Người tạo
        /// </summary>
        [StringLength(450)]
        public string CreateBy { get; set; }
        /// <summary>
        /// Thời gian tạo
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        /// <summary>
        /// Người chỉnh sửa cuối cùng
        /// </summary>
        [StringLength(450)]
        public string LastEditBy { get; set; }
        /// <summary>
        /// Thời gian chỉnh sửa cuối cùng
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? LastEditDate { get; set; }
    }
}