// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMS.Data.ModelEntity
{
    public partial class SpArticleBreadcrumbResult
    {
        public long? Position { get; set; }
        public int? id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string FullUrl { get; set; }
    }
}
